--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: claim; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.claim (
    id bigint NOT NULL,
    claim_date date,
    medication character varying(255),
    pharmacy_name character varying(255),
    status character varying(255),
    member_id bigint
);


ALTER TABLE public.claim OWNER TO postgres;

--
-- Name: claim_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.claim ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.claim_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member (
    id bigint NOT NULL,
    demographics character varying(255),
    dob date,
    first_name character varying(255),
    last_name character varying(255),
    phone_number character varying(255)
);


ALTER TABLE public.member OWNER TO postgres;

--
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: claim; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.claim (id, claim_date, medication, pharmacy_name, status, member_id) FROM stdin;
1	2024-02-01	Advil	Pharmacy One	SUBMITTED	1
2	2024-05-15	Tylenol	Pharmacy Two	SUBMITTED	1
3	2023-12-25	Ibuprofen	Pharmacy Three	DENIED	2
4	2024-07-01	Aspirin	Pharmacy One	APPROVED	2
5	2024-08-30	Naproxen	Pharmacy Four	SUBMITTED	2
6	2023-11-11	Paracetamol	Pharmacy Five	SUBMITTED	3
7	2023-10-01	Amoxicillin	Pharmacy Six	APPROVED	3
8	2024-04-25	Amoxicillin	Pharmacy Six	SUBMITTED	1
\.


--
-- Data for Name: member; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.member (id, demographics, dob, first_name, last_name, phone_number) FROM stdin;
1	male, age 21	2002-04-30	Test	User	8584840089
2	female, age 34	1989-07-20	Jane	Doe	5551234567
3	non-binary, age 27	1996-01-15	Alex	Smith	5559876543
\.


--
-- Name: claim_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.claim_id_seq', 7, true);


--
-- Name: member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.member_id_seq', 1, false);


--
-- Name: claim claim_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.claim
    ADD CONSTRAINT claim_pkey PRIMARY KEY (id);


--
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);


--
-- Name: claim fkb1f4qnsth2py6jn2ufqp2wqb6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.claim
    ADD CONSTRAINT fkb1f4qnsth2py6jn2ufqp2wqb6 FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- PostgreSQL database dump complete
--

